In [1]:
import sqlite3
import pandas as pd

# Load datasets
athletes = pd.read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-07-27/athlete_events.csv")
regions = pd.read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-07-27/noc_regions.csv")
sales = pd.read_csv("https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv")
sales = pd.read_csv("https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv", sep='\t')


# Connect to SQLite in-memory DB
conn = sqlite3.connect(":memory:")

# Write DataFrames to SQL tables
athletes.to_sql("athletes_table", conn, index=False, if_exists="replace")
regions.to_sql("regions_table", conn, index=False, if_exists="replace")
sales.to_sql("sales_table", conn, index=False, if_exists="replace")

4622

In [ ]:
##  Question 1

In [6]:
query_1 = """
SELECT r.region AS Country, COUNT(*) AS Total_medals
FROM athletes_table a
JOIN regions_table r ON a.NOC = r.NOC
WHERE a.Medal IS NOT NULL
GROUP BY r.region
ORDER BY total_medals DESC
LIMIT 5;
"""
pd.read_sql_query(query_1, conn)

   Country  Total_medals
0      USA          5637
1   Russia          3947
2  Germany          3756
3       UK          2068
4   France          1777

In [7]:
query_2 = """
SELECT ROUND(AVG(Age), 2) AS AVG_Gold_Medalist_Age
FROM athletes_table
WHERE Medal = 'Gold';
"""
pd.read_sql_query(query_2, conn)

   AVG_Gold_Medalist_Age
0                   25.9

In [8]:
query_3 = """
SELECT Sport, COUNT(DISTINCT Event) AS Distinct_Events
FROM athletes_table
GROUP BY Sport
ORDER BY Distinct_Events DESC;
"""
pd.read_sql_query(query_3, conn)

            Sport  Distinct_Events
0        Shooting               83
1       Athletics               83
2        Swimming               55
3         Cycling               44
4         Sailing               38
..            ...              ...
61        Cricket                1
62  Basque Pelota                1
63       Baseball                1
64       Alpinism                1
65    Aeronautics                1

[66 rows x 2 columns]

In [9]:
query = """
SELECT *
FROM athletes_table
WHERE NOC = 'USA';
"""

pd.read_sql_query(query, conn)

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
0,6,Per Knut Aaland,M,31.0,188.0,75.0,United States,USA,1992 Winter,1992,Winter,Albertville,Cross Country Skiing,Cross Country Skiing Men's 10 kilometres,NaN
1,6,Per Knut Aaland,M,31.0,188.0,75.0,United States,USA,1992 Winter,1992,Winter,Albertville,Cross Country Skiing,Cross Country Skiing Men's 50 kilometres,NaN
2,6,Per Knut Aaland,M,31.0,188.0,75.0,United States,USA,1992 Winter,1992,Winter,Albertville,Cross Country Skiing,Cross Country Skiing Men's 10/15 kilometres Pu...,NaN
3,6,Per Knut Aaland,M,31.0,188.0,75.0,United States,USA,1992 Winter,1992,Winter,Albertville,Cross Country Skiing,Cross Country Skiing Men's 4 x 10 kilometres R...,NaN
4,6,Per Knut Aaland,M,33.0,188.0,75.0,United States,USA,1994 Winter,1994,Winter,Lillehammer,Cross Country Skiing,Cross Country Skiing Men's 10 kilometres,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18848,135458,Rami Zur,M,27.0,175.0,77.0,United States,USA,2004 Summer,2004,Summer,Athina,Canoeing,"Canoeing Men's Kayak Doubles, 500 metres",NaN
18849,135458,Rami Zur,M,31.0,175.0,77.0,United States,USA,2008 Summer,2008,Summer,Beijing,Canoeing,"Canoeing Men's Kayak Singles, 500 metres",NaN
18850,135458,Rami Zur,M,31.0,175.0,77.0,United States,USA,2008 Summer,2008,Summer,Beijing,Canoeing,"Canoeing Men's Kayak Singles, 1,000 metres",NaN
18851,135543,"Victor Andrew ""Vic"" Zwolak",M,25.0,175.0,64.0,United States,USA,1964 Summer,1964,Summer,Tokyo,Athletics,"Athletics Men's 3,000 metres Steeplechase",NaN
18852,135566,"James Francis ""Jim"" Zylker",M,21.0,175.0,75.0,United States,USA,1972 Summer,1972,Summer,Munich,Football,Football Men's Football,NaN

In [10]:
query_5 = """
SELECT Year, COUNT(*) AS Medals_Awarded
FROM athletes_table
WHERE Medal IS NOT NULL
GROUP BY Year
ORDER BY Year DESC;
"""
pd.read_sql_query(query_5, conn)

    Year  Medals_Awarded
0   2016            2023
1   2014             597
2   2012            1941
3   2010             520
4   2008            2048
5   2006             526
6   2004            2001
7   2002             478
8   2000            2004
9   1998             440
10  1996            1842
11  1994             331
12  1992            2030
13  1988            1845
14  1984            1698
15  1980            1602
16  1976            1531
17  1972            1414
18  1968            1256
19  1964            1215
20  1960            1058
21  1956            1043
22  1952            1033
23  1948             987
24  1936            1025
25  1932             739
26  1928             823
27  1924             962
28  1920            1308
29  1912             941
30  1908             831
31  1906             458
32  1904             486
33  1900             604
34  1896             143

In [14]:
query_6 = """
SELECT *
FROM athletes_table
WHERE Height IS NULL
   OR Weight IS NULL;
"""

pd.read_sql_query(query_6, conn)

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
0,3,Gunnar Nielsen Aaby,M,24.0,175.33897,None,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN
1,4,Edgar Lindenau Aabye,M,34.0,175.33897,None,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
2,8,"Cornelia ""Cor"" Aalten (-Strannood)",F,18.0,168.00000,None,Netherlands,NED,1932 Summer,1932,Summer,Los Angeles,Athletics,Athletics Women's 100 metres,NaN
3,8,"Cornelia ""Cor"" Aalten (-Strannood)",F,18.0,168.00000,None,Netherlands,NED,1932 Summer,1932,Summer,Los Angeles,Athletics,Athletics Women's 4 x 100 metres Relay,NaN
4,10,"Einar Ferdinand ""Einari"" Aalto",M,26.0,175.33897,None,Finland,FIN,1952 Summer,1952,Summer,Helsinki,Swimming,Swimming Men's 400 metres Freestyle,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62870,135539,Marius Edmund Zwiller,M,18.0,175.33897,None,France,FRA,1924 Summer,1924,Summer,Paris,Swimming,Swimming Men's 200 metres Breaststroke,NaN
62871,135542,Werner Zwingli,M,29.0,175.33897,None,Switzerland,SUI,1956 Winter,1956,Winter,Cortina d'Ampezzo,Cross Country Skiing,Cross Country Skiing Men's 15 kilometres,NaN
62872,135542,Werner Zwingli,M,29.0,175.33897,None,Switzerland,SUI,1956 Winter,1956,Winter,Cortina d'Ampezzo,Cross Country Skiing,Cross Country Skiing Men's 4 x 10 kilometres R...,NaN
62873,135552,Jan (Johann-) Zybert (Siebert-),M,20.0,175.33897,None,Poland,POL,1928 Summer,1928,Summer,Amsterdam,Cycling,"Cycling Men's Team Pursuit, 4,000 metres",NaN
62874,135561,Frantiek Zyka,M,26.0,175.33897,None,Czechoslovakia,TCH,1928 Summer,1928,Summer,Amsterdam,Athletics,Athletics Men's Marathon,NaN

In [13]:
#  Run the update query
update_query = """
UPDATE athletes_table
SET Height = (SELECT AVG(Height) 
FROM athletes_table)
WHERE Height IS NULL;
"""
conn.execute(update_query)
conn.commit()

# Verification check
verify_query = """
SELECT COUNT(*) AS missing_heights 
FROM athletes_table 
WHERE Height IS NULL;
"""
pd.read_sql_query(verify_query, conn)

   missing_heights
0                0

In [20]:
query_8 = """
SELECT Item_Name, 
       ROUND(
       SUM(quantity * CAST(
       REPLACE(Item_Price, '$', '') 
       AS REAL)), 2) AS Total_Sales
FROM sales_table
GROUP BY Item_Name
ORDER BY Total_Sales DESC;
"""
pd.read_sql_query(query_8, conn)

                                item_name  Total_Sales
0                            Chicken Bowl      8044.63
1                         Chicken Burrito      6387.06
2                           Steak Burrito      4236.13
3                              Steak Bowl      2479.81
4                     Chips and Guacamole      2475.62
5                      Chicken Salad Bowl      1506.25
6                      Chicken Soft Tacos      1199.01
7            Chips and Fresh Tomato Salsa      1033.96
8                          Veggie Burrito      1002.27
9                             Veggie Bowl       901.95
10                       Barbacoa Burrito       894.75
11                          Carnitas Bowl       830.71
12                          Barbacoa Bowl       672.36
13                          Bottled Water       649.18
14                       Carnitas Burrito       616.33
15                      Canned Soft Drink       603.75
16                                  Chips       580.34
17                       Steak Soft Tacos       554.55
18                   Chicken Crispy Tacos       524.11
19                       Steak Salad Bowl       391.15
20                    Carnitas Soft Tacos       375.94
21                     Steak Crispy Tacos       375.32
22                      6 Pack Soft Drink       369.93
23                          Side of Chips       290.68
24                    Barbacoa Soft Tacos       250.46
25                            Canned Soda       191.84
26                      Veggie Salad Bowl       182.50
27    Chips and Tomatillo Red Chili Salsa       159.30
28  Chips and Tomatillo Green Chili Salsa       144.55
29                  Barbacoa Crispy Tacos       138.71
30                       Nantucket Nectar       111.87
31                    Barbacoa Salad Bowl       106.40
32                  Carnitas Crispy Tacos        95.94
33    Chips and Tomatillo-Red Chili Salsa        93.21
34                      Veggie Soft Tacos        90.94
35  Chips and Tomatillo-Green Chili Salsa        88.43
36                          Chicken Salad        81.09
37                                   Bowl        74.00
38     Chips and Roasted Chili Corn Salsa        73.75
39                                   Izze        67.80
40                    Carnitas Salad Bowl        66.34
41                           Veggie Salad        50.94
42                                Burrito        44.40
43     Chips and Roasted Chili-Corn Salsa        43.02
44                            Steak Salad        35.66
45                                  Salad        14.80
46                           Crispy Tacos        14.80
47                         Carnitas Salad         8.99
48                    Veggie Crispy Tacos         8.49
49      Chips and Mild Fresh Tomato Salsa         3.00

In [21]:
query_9 = """
SELECT * FROM sales_table
ORDER BY CAST(REPLACE(item_price, '$', '') AS REAL) DESC
LIMIT 5;
"""
pd.read_sql_query(query_9, conn)

,order_id,quantity,item_name,choice_description,item_price
0,1443,15,Chips and Fresh Tomato Salsa,NaN,$44.25
1,1398,3,Carnitas Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",$35.25
2,511,4,Chicken Burrito,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$35.00
3,1443,4,Chicken Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",$35.00
4,1443,3,Veggie Burrito,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$33.75

In [23]:
query_10 = """
SELECT COUNT(DISTINCT order_id) AS Unique_Orders
FROM sales_table;
"""
pd.read_sql_query(query_10, conn)

   Unique_Orders
0           1834

In [ ]:
## Question 2

In [24]:
query_section_2 = """
WITH medalists AS (
    SELECT a.ID, a.Age, r.region AS country
    FROM athletes_table a
    JOIN regions_table r ON a.NOC = r.NOC
    WHERE a.ID IN (
        SELECT DISTINCT ID 
        FROM athletes_table 
        WHERE Medal IS NOT NULL
    )
)
SELECT 
    country,
    COUNT(DISTINCT ID) AS medal_winning_athletes,
    ROUND(AVG(Age), 2) AS average_age,
    CASE 
        WHEN AVG(Age) < 25 THEN 'High'
        WHEN AVG(Age) BETWEEN 25 AND 30 THEN 'Medium'
        ELSE 'Low'
    END AS performance
FROM medalists
GROUP BY country
ORDER BY medal_winning_athletes DESC;
"""

# Execute and display the data frame
pd.read_sql_query(query_section_2, conn)

         country  medal_winning_athletes  average_age performance
0            USA                    3851        25.55      Medium
1         Russia                    2630        25.16      Medium
2        Germany                    2572        25.66      Medium
3             UK                    1604        28.16      Medium
4         France                    1279        28.25      Medium
..           ...                     ...          ...         ...
133      Curacao                       1        19.00        High
134     Botswana                       1        20.00        High
135      Bermuda                       1        25.00      Medium
136     Barbados                       1        23.20        High
137  Afghanistan                       1        23.00        High

[138 rows x 4 columns]